FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
COPY . .
RUN npm run build

RUN nginx:alpine
copy --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
